### ISSUE TITLE
@Resolver() does not work with typedi 0.10.0

### ISSUE THREAD

**Issue by tonynguyenit18** [MichalLytek/type-graphql#893] opened 2021-05-24 07:45 UTC
**Issue**
I have a resolver
```
@Resolver()
export class AssessmentResolver {
  constructor(private readonly assessmentService: AssessmentService) {}
  @Query(() => Assessment, { name: "FIGetAssessment" })
  async getAssessment(@Arg("id") id: string): Promise<Assessment> {
    return this.assessmentService.findById(id)
  }
}
```ts
And register the resolver in app
```ts
  const schema = await buildSchema({
    resolvers: [AssessmentResolver],
    emitSchemaFile: path.resolve(__dirname, "schema.gql"),
    container: Container
  })
```
It was working fine with `"typedi:0.8.0"`

But when I upgrade `typedi` to `0.10.0` I got the `ServiceNotFoundError` error

**Logs**
```
{
  "errors": [
    {
      "message": "Service with \"MaybeConstructable<AssessmentResolver>\" identifier was not found in the container. Register it before usage via explicitly calling the \"Container.set\" function or using the \"@Service()\" decorator.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "FIGetAssessment"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "name": "ServiceNotFoundError",
          "normalizedIdentifier": "MaybeConstructable<AssessmentResolver>",
          "stacktrace": [
            "ServiceNotFoundError: Service with \"MaybeConstructable<AssessmentResolver>\" identifier was not found in the container. Register it before usage via explicitly calling the \"Container.set\" function or using the \"@Service()\" decorator.",
            "    at ContainerInstance.get (/app/node_modules/typedi/cjs/container-instance.class.js:45:15)",
            "    at Function.get (/app/node_modules/typedi/cjs/container.class.js:28:36)",
            "    at IOCContainer.getInstance (/app/node_modules/type-graphql/dist/utils/container.js:39:26)",
            "    at /app/node_modules/type-graphql/dist/resolvers/create.js:15:51",
            "    at field.resolve (/app/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:466:18)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:294:18)",
            "    at executeOperation (/app/node_modules/graphql/execution/execute.js:238:122)",
            "    at executeImpl (/app/node_modules/graphql/execution/execute.js:118:14)",
            "    at Object.execute (/app/node_modules/graphql/execution/execute.js:62:35)",
            "    at /app/node_modules/apollo-server-core/dist/requestPipeline.js:261:48",
            "    at Generator.next (<anonymous>)",
            "    at /app/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/app/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)",
            "    at execute (/app/node_modules/apollo-server-core/dist/requestPipeline.js:240:20)"
          ]
        }
      }
    }
  ],
  "data": null
}
``` 

I also tried to add `@Service` followed this example https://typegraphql.com/docs/dependency-injection.html, but I get `Maximum call stack size exceeded` error.

So I try with `{ isAbstract: true }`, 
```ts
@Service()
@Resolver({ isAbstract: true })
export class AssessmentResolver {
  constructor(private readonly assessmentService: AssessmentService) {}
  @Query(() => Assessment, { name: "FIGetAssessment" })
  async getAssessment(@Arg("id") id: string): Promise<Assessment> {
    return this.assessmentService.findById(id)
  }
}
```
but seem like entire queries and mutations is disappear from playground docs

**Expected Behavior**
The Application shout not be broken at all

**Environment (please complete the following information):**

- OS: [linux (Docker container)]
- Node 12.13.x
- TypeScript version "^4.2.4"
- "type-graphql": "1.1.1",
- "typedi": "0.10.0"

**Comment by MichalLytek** [comment] 2021-05-24 07:47
Duplicate of #775 #840 🔒 

> I also tried to add @Service followed this example but I get Maximum call stack size exceeded error.

Report in TypeDI repo.

**Closed by MichalLytek** 2021-05-24 07:47 UTC

**Comment by tonynguyenit18** [comment] 2021-05-24 08:03
> So I try with { isAbstract: true },
    ```
    @Service()
    @Resolver({ isAbstract: true })
    export class AssessmentResolver {
    constructor(private readonly assessmentService: AssessmentService) {}
       @Query(() => Assessment, { name: "FIGetAssessment" })
        async getAssessment(@Arg("id") id: string): Promise<Assessment> {
          return this.assessmentService.findById(id)
        }
     }
     ```
but seem like entire queries and mutations is disappear from playground docs

What about this situation @MichalLytek

**Comment by MichalLytek** [comment] 2021-05-24 08:12
> entire queries and mutations is disappear from playground docs

TypeGraphQL uses containers in the runtime, not to build the schema. So you've made a mistake in another place.
