### ISSUE TITLE
No matter the validation error, I still get generic `Argument Validation Error` message

### ISSUE THREAD

**Issue by geauser** [MichalLytek/type-graphql#1401] opened 2022-12-19 18:46 UTC
**Describe the Bug**
When there is an error caught by `class-validator` decorators on `@InputType()` for mutations _(example `@MinLength`)_, I only get a generic `"Argument Validation Error"` message. 

Furthermore specifying [a custom validation message as documented in `class-validator`](https://github.com/typestack/class-validator#validation-messages) doesn't change anything.

**To Reproduce**
I made a [dedicated repo](https://github.com/geauser/type-graphql-issue) to reproduce the problem.

When the server is up, executes this query on [`http://localhost:4444/gql`](http://localhost:4444/gql):
```graphql
mutation { 
    addAccount(data: { name: "Invalid" }) { name }
}
```

**Expected Behavior**
I'd expect to see the validation message set for the given `class-validator` decorator _(or the default one)_.

**Logs**
```json
{
    "errors": [
        {
            "message": "Argument Validation Error",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "addAccount"
            ]
        }
    ],
    "data": null
}
```

**Environment**

- OS: MacOS 12.4 Monterey
- Node `v16.13.2`
- Package version `^2.0.0-beta.1`
- TypeScript version `^4.9.4`

**Comment by MichalLytek** [comment] 2022-12-19 18:53
Is it a duplicate of #1396 ?

**Comment by geauser** [comment] 2022-12-19 18:59
Hmm does not seem like it. Passing `{ forbidUnknownValues: false }` changes nothing.

**Comment by carlocorradini** [comment] 2022-12-19 22:52
Duplicate of #1397 
The GraphQL error encapsulates the original error.
You must create a custom function (`formatError`) when building an Apollo server instance.
It's all described in this comment: https://github.com/MichalLytek/type-graphql/issues/1397#issuecomment-1351432122

**Closed** 2022-12-20 07:10 UTC
Labels: Duplicate :key:
