### ISSUE TITLE
Nested resolvers

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MichalLytek/type-graphql#781] opened 2021-02-05 20:50 UTC
Hello,

I am building API and want to grup it by type e.g. 

```
query {
	users {
  	    getByEmail(email:"ippame@jo.gq") {
  	        _id
  	        email
  	        name
  	        dateOfBirth
  	        phone
  	        profilePicture
  	        gender
                  
  	    }
	}
}
```

Earlier i was using pure Apollo with graphql types an it was possible by passing empty resover as root like this

```
fields: () => ({
        users: { type: UserQueries, resolve: () => [] },
    }) as any,


export const UserQueries = new GraphQLObjectType<any, any, any>({
    name: 'UserQueries',
    fields: () => ({
        getByEmail: {
            type: UserType,
            description: UserType.description,
            args: typedArgs<GetByEmailRequest>({
                locale: { type: GraphQLNonNull(GraphQLString) },
                email: { type: GraphQLNonNull(GraphQLString) },
            }),
            resolve: (_: any, args: GetByEmailRequest) => userService.getByEmail(args.email),
        },
    }),
});
```

I have found few pproaches in your git issues list but there people using field resolvers taking results from root. I do not want this - i just want to have one nesting level with "pass through" arguments.

How can I achieve this?

**Comment by MichalLytek** [comment] 2021-02-05 21:31
> How can I achieve this?

You can't 😉 

> there people using field resolvers taking results from root

That's what you need to do 😛 

GraphQL is about graphs and nodes - making namespaces for grouping fields is not GraphQL idiomatic and there won't be support for such API design mistakes.

Closing as duplicate of #712 #312 #64 🔒

**Closed by MichalLytek** 2021-02-05 21:31 UTC
