### ISSUE TITLE
[1.0.0-rc1] class-validator is peer dependency but seems to be required?

### ISSUE THREAD

**Issue by rchl** [MichalLytek/type-graphql#625] opened 2020-05-06 08:48 UTC
**Describe the Bug**
Trying to compile project using rc1 version results in type errors because types for `class-validator` are not available.

**To Reproduce**
1) Checkout https://github.com/rchl/type-graphql-class-validator 
2) Run `npm i`
3) Run `npm run build`

**Expected Behavior**
Build succeeds.

**Logs**
```
> tsc

node_modules/type-graphql/dist/decorators/types.d.ts:2:39 - error TS2307: Cannot find module 'class-validator'.

2 import type { ValidatorOptions } from "class-validator";
                                        ~~~~~~~~~~~~~~~~~

node_modules/type-graphql/dist/errors/ArgumentValidationError.d.ts:1:38 - error TS2307: Cannot find module 'class-validator'.

1 import type { ValidationError } from "class-validator";
                                       ~~~~~~~~~~~~~~~~~

node_modules/type-graphql/dist/metadata/definitions/param-metadata.d.ts:1:39 - error TS2307: Cannot find module 'class-validator'.

1 import type { ValidatorOptions } from "class-validator";
                                        ~~~~~~~~~~~~~~~~~

node_modules/type-graphql/dist/schema/build-context.d.ts:2:39 - error TS2307: Cannot find module 'class-validator'.

2 import type { ValidatorOptions } from "class-validator";
                                        ~~~~~~~~~~~~~~~~~
```

**Environment (please complete the following information):**

- OS: macos
- Node 10.19.0
- Package version 1.0.0-rc1
- TypeScript version 3.8.3

**Comment by MichalLytek** [comment] 2020-05-06 08:50
https://typegraphql.com/docs/validation.html#caveats

**Comment by rchl** [comment] 2020-05-06 08:54
OK, that clearly addresses my issue :)

**Comment by rchl** [comment] 2020-05-06 08:56
Can maybe release notes be updated to mention that?
Currently they say `Breaking Change: make class-validator an optional, peer dependency of version >=0.12.0` which gives an impression that it's not needed.

**Comment by MichalLytek** [comment] 2020-05-07 18:10
The goal is to have a separate plugin for validation that will be optional and installing `class-validator` won't be required.

For now, due to the typings issue with compiling, caused by monolith architecture, you need to have `class-validator` installed as a dev deps (when not using validation) or `skipLibCheck` set to `true`.

@rchl 
What do you think is better - `npm i class-validator` in installation docs or `skipLibCheck: true` as the default recommended setting?

**Comment by rchl** [comment] 2020-05-07 18:30
@MichalLytek I think it's better to have `npm i class-validator` as that is localized to this package and doesn't have type checking side effects on the whole project.

**Comment by MichalLytek** [comment] 2020-05-10 18:19
@rchl 
Actually, that's what I've done over a month ago:

![image](https://user-images.githubusercontent.com/10618781/81507124-6bb9b280-92fb-11ea-8cc5-c4e92030c381.png)

So I will just remove the "optional" info from release notes as they might be confusing.

**Comment by MichalLytek** [comment] 2020-05-10 18:22
Closing by 930a692 🔒

**Closed** 2020-05-10 18:21 UTC
Labels: Community  :family_man_girl:, Documentation :book:, Solved :heavy_check_mark:
