### ISSUE TITLE
Crash after graphql updates

### ISSUE THREAD

**Issue by KirillBychkov** [MichalLytek/type-graphql#609] opened 2020-04-19 13:36 UTC
**Environment**
- OS: Linux Ubuntu 18
- Node 13.7
- Package version 0.17.6
- TypeScript version 3.8.3
- "@nestjs/core": "^7.0.8",
- "@nestjs/graphql": "^7.3.1",
- "graphql": "^15.0.0",
- "graphql-tools": "^5.0.0",

![Screenshot_20200419_162657](https://user-images.githubusercontent.com/32789602/79688966-995e8f00-825a-11ea-9017-7f9896a5d232.png)

**Additional Context**
Hello. I am use package _ncu_ to update my nestjs/graphql project to latest versions. After updates it can't build =(

For this prev versions it works good 
    "@nestjs/core": "^6.11.5",
    "@nestjs/graphql": "^6.5.3",
    "graphql": "^14.6.0",
    "graphql-tools": "^4.0.6",

**Comment by MichalLytek** [comment] 2020-04-19 13:38
Duplicate of #594 🔒 

Please read the npm install warning about missing peer dependencies - they would have told you that you can't use graphql 15 yet, only 14.6 is supported.

**Closed by MichalLytek** 2020-04-19 13:38 UTC

**Comment by KirillBychkov** [comment] 2020-04-19 13:43
Oh, thanks) I will wait
