### ISSUE TITLE
Generated schema included all resolvers when using inversifyjs container

### ISSUE THREAD

**Issue by xinghul** [MichalLytek/type-graphql#622] opened 2020-05-02 03:57 UTC
**Describe the Bug**
Not sure if this is a bug, probably a feature request instead.

I have a use case where I want to separate resolvers into 2 groups: admin resolvers and public resolvers, and generate two different schemas.
However, I noticed that the public schema generate contained all the resolvers(including the private admin resolvers).
Here's the code snippet for generating public schema:
```javascript
const schema = await TypeGraphQL.buildSchema({
  resolvers: values(publicResolvers),
  emitSchemaFile: {
    path: path.join(__dirname, '../../schema.public.gql'),
    commentDescriptions: true,
  },
});
```
`publicResolvers` only contains the public resolvers, but I do have all the resolvers binded to a container(inversifyjs), looks like the container resolvers took precedence, that might be the reason why.

Is there a way to generate the schema based the resolvers passed in?

Thanks!

**Comment by MichalLytek** [comment] 2020-05-02 07:36
Please fill the bug report issue form as it may contain valuable info for helping you.

**Comment by MichalLytek** [comment] 2020-05-02 11:33
It's obviously a duplicate of #234 which is fixed in `type-graphql@beta`, so closing this one 🔒

**Closed by MichalLytek** 2020-05-02 11:33 UTC
Labels: Need More Info :man_shrugging:, Question :grey_question:
