### ISSUE TITLE
Unions schema generator issue

### ISSUE THREAD

**Issue by pereslavtsev** [MichalLytek/type-graphql#410] opened 2019-08-30 10:32 UTC
**Describe the bug**
I have this error during building a project:
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
`
during assembly

**To Reproduce**
I created a new union:
`
import { createUnionType } from 'type-graphql';

export const EventDataUnion = createUnionType({
  name: 'EventData',
  types: () => [Conversation, Message, Contact],
});`

 then new query and use the union:
```
 @Query(returns => EventDataUnion)
  async getData(@Parent() { id }: Event): Promise<any> {
     // any code
  }
```

but after rebuild a schema I get the error
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
`

**Expected behavior**
Schema should be generated, I followed the docs - https://typegraphql.ml/docs/unions.html

**Logs**
It seems `getClassTypes` arrow functions doesn't resolves, I have undefined value of property `classTypes`:
```
{ name: 'EventData',
  description: undefined,
  getClassTypes: [Function: types],
  resolveType: [Function: resolveType],
  symbol: Symbol(EventData) }
```
unionMetadata contains this data before this line - https://github.com/MichalLytek/type-graphql/blob/master/src/schema/schema-generator.ts#L155 

**Enviorment (please complete the following information):**
 - Mac OS 10.14
 - Node 11.5.0
 - Package version 0.17.5
 - TypeScript version 3.5.3

**Comment by MichalLytek** [comment] 2019-08-30 10:37
Duplicate of #407 🔒

**Closed by MichalLytek** 2019-08-30 10:37 UTC
