### ISSUE TITLE
FieldOption name does not work on @InputType. It is dropped when the Input is parsed.

### ISSUE THREAD

**Issue by odedsh** [MichalLytek/type-graphql#1101] opened 2021-10-31 10:49 UTC
**Describe the Bug**
When building an @InputType using a complex object with @Field and the FieldOption name.

type-graphql generates a sensible schema. But drops the field when parsing the input.

**To Reproduce**

```
@InputType()
export class ComplexType {
  @Field({name:"status", nullable: true})
  appStatus?: string
}

@Query
async func(
    @Arg('val', () => ComplexType , {  nullable: true })
      appStatus?: ComplexType ,
): Promise<>{
   console.log(` ! ${JSON.stringify(appStatus)} !`);
   return ...
}

```

**Expected Behavior**
When called with an input like 
```
val { status:"any"}
```

I expect to see `! {"appStatus": "any"} !`
Instead I see `! {} !`

**Environment (please complete the following information):**

- OS: Linux
- Node 12
- Package version 1.1.1
- TypeScript version 4.2

**Comment by MichalLytek** [comment] 2021-10-31 13:30
Duplicate of #346 🔒

**Closed by MichalLytek** 2021-10-31 13:30 UTC
