### ISSUE TITLE
Mutation return type Promise<boolean> not inferreed as boolean

### ISSUE THREAD

**Issue by etudor** [MichalLytek/type-graphql#527] opened 2020-01-22 16:22 UTC
**Describe the bug**
Promise<boolean> not resolved in mutation and this error is produced: 
```
Error: You need to provide explicit type for default_1#deleteOrder !
```

**To Reproduce**
```
  @Authorized()
  @Mutation()
  async deleteOrder(
    @Arg('id', type => Int) id: number
  ): Promise<boolean> {
    const order = await OrderRepository.findById(id)
    order.deletedAt = new Date()

    await OrderRepository.save(order)

    return true
  }
```

**Expected behavior**
The output of the mutation should be inferred as `boolean` from the return type

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.

**Enviorment (please complete the following information):**
 - OS: Docker on Windows
 - Node: v13.6.0
 - Package version: 0.17.5
 - TypeScript version: 3.7.3

**Additional context**

**Comment by MichalLytek** [comment] 2020-01-22 16:23
Duplicate of #296 🔒

**Closed by MichalLytek** 2020-01-22 16:23 UTC

**Comment by etudor** [comment] 2020-01-22 16:27
I agree this is duplicate. But I find it to be a bug and not an enhancement. Because Boolean is not a type in type-graphql how can I manually set the return type in my case? 
```
@Mutation(returns => Boolean) ### this won't work
```
Is there a quick solution for this until the enhancement is added?

**Comment by MichalLytek** [comment] 2020-01-22 16:30
@etudor this has to work
```ts
  @Mutation(returns => Boolean)
  async deleteOrder(
    @Arg('id', type => Int) id: number
  ): Promise<boolean> {}
```

**Comment by Jonasdoubleyou** [comment] 2021-07-19 17:49
FWIW the documentation can now be found at https://typegraphql.com/docs/scalars.html , the .ml domain seems to belong to a different entity now.
