### ISSUE TITLE
Fields with type Enum are taking enum keys instead of enum values on graphql mutations

### ISSUE THREAD

**Issue by lewispham** [MichalLytek/type-graphql#742] opened 2020-10-26 12:00 UTC
**Describe the Bug**
I'm having an issues with enum values pass through grahpql mutation. Basically it looks like enum keys are taken as values. It's working ok with `@Query` but `@Mutation`.

**To Reproduce**
```
@Entity()
@ObjectType()
export class User {
    ...

    @Field(() => UserStatus)
    @Enum({nullable: false, length: 20})
    status = UserStatus.Created;

    ...
}


// interface
import { registerEnumType } from "type-graphql";

export enum UserStatus {
    Created = "CREATED",
    Verified = "VERIFIED",
    PendingVerification = "PENDING_VERIFICATION",
    Activated = "ACTIVATED"
}

registerEnumType(UserStatus, {
    name: "UserStatus"
});

// Resolver
@Mutation(() => User)
async verifyEmail(@Ctx() ctx: IGraphQLRequestContext): Promise<User> {
    return new UserService(ctx).verifyEmail();
}

// Query
mutation VerifyingEmail {
  verifyEmail {
    id
    status
  }
}

// Output

{
  "data": {
    "verifyEmail": {
      "id": "57",
      "status": "Verified"  
    }
  }
}
```
**Expected Behavior**
Enum values should be taken instead of enum keys

**Expected output**
```
{
  "data": {
    "verifyEmail": {
      "id": "57",
      "status": "VERIFIED"  
    }
  }
}
```

**Environment (please complete the following information):**

- OS: [e.g. Windows] MacOS
- Node (e.g. 10.5.0) 14.10.0
- Package version [e.g. 0.12.2] (please check if the bug still exist in newest release) 1.0.0
- TypeScript version (e.g. 2.8.2) 4.0.2

**Comment by MichalLytek** [comment] 2020-10-26 12:05
> Enum values should be taken instead of enum keys

Duplicate of #741 🔒 

> It's working ok with @Query but @Mutation.

So it's definitely an error in your codebase (`UserService`).

**Closed by MichalLytek** 2020-10-26 12:05 UTC

**Comment by lewispham** [comment] 2020-10-26 14:07
@MichalLytek If the motivation behinds the current behavior is about graphql enum only supports keys as string, then I think it's better to throw an error when the enum key is invalid instead of silently taking the key as value. Using key as value will probably cause confusions in our code base.

**Comment by MichalLytek** [comment] 2020-10-26 14:09
It's not silently taking key as value. Read the docs first before creating such issues.
