### ISSUE TITLE
Property is called before FieldResolver when annotated with @Field

### ISSUE THREAD

**Issue by fromi** [MichalLytek/type-graphql#607] opened 2020-04-17 16:47 UTC
**Describe the Bug**
I have a FieldResolver, which works fine. However, as soon as I also annotate the property it resolves with `@Field()` annotation, the field resolver is not called anymore. However, I red that FieldResolver should take precedence over the property.

**To Reproduce**
Here is my simplified schema:
```
@ObjectType()
export class Player {
  constructor(userId: string) {
    this.userId = userId
  }

  private readonly userId!: string

  isControlledBy(userId: string): boolean {
    return this.userId == userId
  }

  @Field()
  isMe: boolean = false
}

@Resolver(() => Player)
export class PlayerResolver implements ResolverInterface<Player> {
  @FieldResolver(() => Boolean)
  isMe(@Root() player: Player, @Ctx('userId') userId: string) {
    return player.isControlledBy(userId)
  }
}
```

**Expected Behavior**
`@FieldResolver` should take precedence over `@Field`

**Additional Context**
I use version 0.18.0-beta.10. I could not get version 0.18.0-beta.16 to work because GraphQL dependency is not properly declared and it fails at runtime:
_Error: Looks like you use an incorrect version of the 'graphql' package: "14.5.8". Please ensure that you have installed a version that meets TypeGraphQL's requirement: "^14.6.0"._

**Comment by MichalLytek** [comment] 2020-04-18 09:52
Your example has no `@Query` so I can't reproduce the issue if you don't show how you return the `player` object.

Please try to reproduce the issue without your potentially faulty business logic - create a simple object type:
```ts
@ObjectType()
export class Player {
  @Field()
  isMe: boolean = false
}
```

and as your field has default value `false`, create this field resolver:
```ts
  @FieldResolver()
  isMe() {
    return true;
  }
}
```
and this simple example query:
```ts
@Resolver(() => Player)
export class PlayerResolver implements ResolverInterface<Player> {
  @Query(() => Player )
  player() {
    return new Player();
  }
}
```

With this constraints, I cannot reproduce the reported behavior - "Property is called before `@FieldResolver` when annotated with `@Field`". It correctly returns value `true` from the query `player { isMe }`, so please again check and debug your real code.

**Comment by fromi** [comment] 2020-04-18 11:26
Hi @MichalLytek, thanks for the help!
So, I updated my code as you said, I did that:
```
@ObjectType()
export class Player {
  constructor(userId?: string) {
    this.userId = userId || ""
  }

  @prop()
  private readonly userId!: string

  isControlledBy(userId: string): boolean {
    return this.userId == userId
  }

  @Field()
  isMe: boolean = false
}

@Resolver(() => Player)
export class PlayerResolver implements ResolverInterface<Player> {
  @Query(() => Player)
  player() {
    return new Player();
  }

  @FieldResolver(() => Boolean)
  isMe() {
    return true
  }
}
```
I called this very simple query: `{ player {isMe} }`
And the result is: `{"data":{"player":{"isMe":false}}}`
So the FieldResolver is once again ignored.
Then I remove the `@Field` annotation on "isMe" property, and the result this time is correct: `{"data":{"player":{"isMe":true}}}`

I can see the difference also when I add a log inside the resolver: it is called only when I do not annotate the property.

**Comment by MichalLytek** [comment] 2020-04-18 11:30
I've created a test case for that but I cannot reproduce the issue 😕 

Please update to newest `beta.17` version with upgrading `graphql` package.
If the error still happening, please create a repository with a minimal reproducible code example.

**Comment by MichalLytek** [comment] 2020-04-18 11:33
```ts
import "reflect-metadata";
import * as path from "path";
import { ApolloServer } from "apollo-server";
import {
  ObjectType,
  Field,
  ResolverInterface,
  FieldResolver,
  Resolver,
  Query,
  buildSchema,
} from "../../src";

@ObjectType()
export class Player {
  @Field()
  isMe: boolean = false;
}

@Resolver(() => Player)
class PlayerResolver implements ResolverInterface<Player> {
  @Query(() => Player)
  player() {
    return new Player();
  }

  @FieldResolver(() => Boolean)
  isMe() {
    return true;
  }
}

async function bootstrap() {
  // build TypeGraphQL executable schema
  const schema = await buildSchema({
    resolvers: [PlayerResolver],
    // automatically create `schema.gql` file with schema definition in current folder
    emitSchemaFile: path.resolve(__dirname, "schema.gql"),
  });

  // Create GraphQL server
  const server = new ApolloServer({
    schema,
    // enable GraphQL Playground
    playground: true,
  });

  // Start the server
  const { url } = await server.listen(4000);
  console.log(`Server is running, GraphQL Playground available at ${url}`);
}

bootstrap();
```

![image](https://user-images.githubusercontent.com/10618781/79636601-377a2880-8179-11ea-812d-53cfde42dca4.png)

**Comment by fromi** [comment] 2020-04-18 15:29
I am trying to update to `beta.17`, however I have this error at runtime:
`Looks like you use an incorrect version of the 'graphql' package: "14.5.8". Please ensure that you have installed a version that meets TypeGraphQL's requirement: "^14.6.0".`

So, I try to add this in my package dependencies: `"graphql": "^14.6.0"`, but then I have this new error:
`Error: GraphQL error: Cannot find module 'class-validator'`

I'm digging into package-lock.json for hints now, but if you know what is happening it would help a lot :)

**Comment by fromi** [comment] 2020-04-18 15:34
It looks like I have `apollo-server-core` version `2.12.0` which depends on `"@types/graphql-upload": "^8.0.0"`, which itself depends on `"graphql": "^14.5.3"`
When I force graphql version in my dependencies, I run into the class-validator issue.

**Comment by MichalLytek** [comment] 2020-04-18 15:38
> Cannot find module 'class-validator'

Have you tried installing it? Or at least reading the changelog as you update the package? 🤔 

https://github.com/MichalLytek/type-graphql/blob/master/CHANGELOG.md

**Comment by fromi** [comment] 2020-04-18 15:42
Just got to it! About graphql version, it looks like deleting the version I have to force update to 14.6.0 works too, no need for the dependency.

**Comment by fromi** [comment] 2020-04-18 15:45
So, now that I added "class-validator" dependency (which fixes a lot of warnings btw 👍), I can run my project with version beta17!
And I can still reproduce the issue where the property takes precedence over my FieldResolver as soon as I add the Field annotation on it...

**Comment by MichalLytek** [comment] 2020-04-18 16:17
> And I can still reproduce the issue where the property takes precedence over my FieldResolver as soon as I add the Field annotation on it...

Please create a repository with a minimal reproducible code example.

**Comment by fromi** [comment] 2020-04-18 16:26
Nope, your test case is probably right. It's probably some weird side effect of using Typegoose and Type-graphql annotations on the same class.

I have an easy workaround: not annotating my properties with `@Field` when I need a FieldResolver, and specifying the type of the property on the resolve.

You may close this issue if you wish! This discussion might help people scratching their head with the same problem I guess.

**Comment by MichalLytek** [comment] 2020-04-18 16:28
> It's probably some weird side effect of using Typegoose and Type-graphql annotations on the same class.

If you locate in which cases and why, feel free to leave the comment here in this thread.

> This discussion might help people scratching their head with the same problem I guess.

As it's not a valid bug report, I'm gonna close this issue but it still be searchable in the repository 😉

**Closed by MichalLytek** 2020-04-18 16:28 UTC
Labels: Community  :family_man_girl:, Need More Info :man_shrugging:

**Comment by filipsuk** [comment] 2020-10-12 14:34
@fromi I have the same issue and I use the same workaround. Have you found a solution by any chance?

**Comment by fromi** [comment] 2020-10-12 15:20
> @fromi I have the same issue and I use the same workaround. Have you found a solution by any chance?

Yes, as written in my last comment : 
> I have an easy workaround: not annotating my properties with @Field when I need a FieldResolver, and specifying the type of the property on the resolve.
