### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by mahaben** [MichalLytek/type-graphql#449] opened 2019-10-21 09:11 UTC
**Describe the bug**
We are facing a memory leak issue. We have a graphql query that returns 1200 records and called every 10 seconds. Memory keeps increasing over time and never released when the query is stopped.

**To Reproduce**
-Create a simple entity 
-Create a graphql query that returns 1000 records of this entity
-Create a graphql client that calls this query every 10 secs
-Inspect memory

**Expected behavior**
-Memory should be released

**Logs**
<img width="589" alt="Capture d’écran 2019-10-21 à 11 09 31" src="https://user-images.githubusercontent.com/12132174/67192128-4dd64000-f3f3-11e9-8f07-6919258e0227.png">

**Environment (please complete the following information):**
 - Node (12.11.1)
 - Package version [^0.17.5]
 - TypeScript version (^3.6.4)

Thanks.

**Comment by MichalLytek** [comment] 2019-10-21 14:47
> Memory should be released

What memory? Metadata from decorators?

The only memory leak that could happen is that you construct the schema multiple times, so e.g. when you use lambda/serverless that shares the same Node.js process but executes modules evaluation and run the schema build on every request.

If you want me to tackle this issue, please help and provide more detailed info what does the metadata storage contains, e.g. if the fields that contains all collected metadata like `resolvers` has the same length as the number of your resolvers in app. Maybe you store some additional data in the class instances of static properties so the debugger shows that the metadata storage has 600 MB of data.

**Comment by mahaben** [comment] 2019-10-21 15:02
@MichalLytek The schema is constructed once at the server start not on every request.

You can use this repo to reproduce https://github.com/mahaben/graphql

Thanks.

**Comment by MichalLytek** [comment] 2019-10-24 20:16
This repo has very outdated dependencies (`type-graphql 0.15.0`), no package lock and I can't build the app:
```
PS F:\#Projekty\#Github\typegraphql-memory-leak> npm run build

> graphql-typescript@1.0.0 build F:\#Projekty\#Github\typegraphql-memory-leak
> tsc

node_modules/subscriptions-transport-ws/dist/server.d.ts:2:28 - error TS7016: Could not find a declaration file for module 'ws'. 'F:/#Projekty/#Github/typegraphql-memory-leak/node_modules/ws/index.js' implicitly has an 'any' type.  
  Try `npm install @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

2 import * as WebSocket from 'ws';
                             ~~~~
Found 1 error.
```

**Comment by MichalLytek** [comment] 2019-10-24 20:23
Fixed the errors, run the app, call many queries - cannot reproduce, everything looks ok, memory grows to 35MB and then it's garbage collected.

Please create a full reproduction detailed instruction with repo, node version, steps to record memory, etc. Otherwise will close the issue as invalid.

**Comment by mahaben** [comment] 2019-10-25 08:21
Hello,

Maybe I was not clear about how to reproduce this bug using the repo. Have you followed these steps?

-Start the server in `index.ts`
-Take a snapshot of memory
-Start multiple clients using `client.ts` (10 for example)
-Wait about 1 hour
-Stop clients 
-Take again a memory snapshot 

Thanks,

**Comment by Marsup** [comment] 2019-10-25 09:59
I've been able to reproduce this leak, but my best guess is that it's the same as https://github.com/nodejs/node/issues/28420. There is no leak on node 10 while there's a massive one on node 12. Unless your library specifically triggers the leak, I'm afraid there's not much you can do.

**Comment by MichalLytek** [comment] 2019-10-27 09:03
> More ...Retained size shows 600MB
> 
> I think that there is a real memory leak problem. I can't reproduce this behavior using classic `graphql`. Any Idea?
> 
> Thanks.
> 
> <img alt="Capture d’écran 2019-10-19 à 15 20 50" width="1171" src="https://user-images.githubusercontent.com/12132174/67145730-139a6080-f284-11e9-897d-714dbce684fe.png">

I tried to reproduce the issue but on Node `v12.11.1` after an hour of querying I still have the same fixed size of TypeGraphQL metadata storage:

![Code_2019-10-27_10-29-32](https://user-images.githubusercontent.com/10618781/67632162-4d7cef80-f8a0-11e9-82a1-1c75f1634126.png)

After stopping the queries it grew up for a few kBs. The overall memory consumption grows really big up to ~120MB (from initial 12MB) and then after disconnecting the client went to ~200MB 😕 

So I think the issue is not related to TypeGraphQL (the amount of registered resolvers or fields is the same, no rebuidling the schema), maybe it's a Node.js version issue or some libs like Apollo Server and websockets, I don't know.

**Comment by MichalLytek** [comment] 2019-11-01 17:26
Closing as no response from OP, I cannot reproduce and it might be Node.js version related issue 🔒

**Closed by MichalLytek** 2019-11-01 17:26 UTC
Labels: Bug :bug:, Community  :family_man_girl:, Need More Info :man_shrugging:

**Comment by MichalLytek** [comment] 2019-12-05 21:10
@mahaben 
Please check the newest `v0.18.0-beta.7` - it has a build done for `ES2018` target with async/await so it should be much more memory efficient 😉

**Comment by mahaben** [comment] 2020-01-09 14:12
@MichalLytek thanks for the `v0.18.0-beta.7`, it seems to resolve the memory leak. But I get some error `GraphQLError: Unknown type, validation failed`  when using inheritance. The error is not present using the release `0.17.6`. Any idea of what changed between the two versions?

**Comment by MichalLytek** [comment] 2020-01-09 14:13
> Any idea of what changed between the two versions?

Now we build only explicitly referenced types - you may need to put the interfaces or other types into the `orphanedTypes` array.

**Comment by mahaben** [comment] 2020-01-09 14:32
Hmm, don't know what i'm doing wrong, here is my code:

<img width="478" alt="Capture d’écran 2020-01-09 à 15 31 29" src="https://user-images.githubusercontent.com/12132174/72076019-222d6c80-32f5-11ea-8540-7c6501609507.png">

`ActorTaskResolver`  is abstract and `ActorTaskChooseGroupsResolver` extends `ActorTaskResolver`

**Comment by MichalLytek** [comment] 2020-01-09 14:36
`orphanedTypes` is not for resolvers! 
It's for the case like you have an interface `IPerson` that you use as response type of `users` query and then two object type classes `Student` and `Employee` that implements that interface. 
In the v0.18 pipeline they are not emitted in schema as not directly referenced, so the returned interface has no implementation found and you receive "Unknown type" I guess.

**Comment by mahaben** [comment] 2020-01-09 14:42
So what should I do to have these resolvers in the schema to avoid this error? Indeed, the resolvers are present in the schema generated in v0.17 and not in v0.18 🤔

**Comment by MichalLytek** [comment] 2020-01-09 14:46
Put them in the `resolvers` array! 😠

**Comment by mahaben** [comment] 2020-01-09 14:51
😄 this is already the case !! but it doesn't work :(

**Comment by MichalLytek** [comment] 2020-01-09 14:52
Is it an abstract repository?

Maybe it will be faster for you to create a repository with a minimal reproducible code example (not a dump from your project codebase) and create a new issue with that.

**Comment by mahaben** [comment] 2020-01-09 15:13
Thanks, I'll create a repo to reproduce.

**Comment by mahaben** [comment] 2020-01-09 16:45
@MichalLytek it's okay, solve it 🎉 . Thanks.
