### ISSUE TITLE
Union type doesn't work when running two schemas together

### ISSUE THREAD

**Issue by bkstorm** [MichalLytek/type-graphql#583] opened 2020-03-20 02:44 UTC
**Describe the bug**
I'm building two schemas: one for the mobile application and another one for the admin website.
```typescript
  const adminSchema = await buildSchema({
    resolvers: [NotificationObjectResolver]
  });
  const mobileSchema = await buildSchema({
    resolvers: [NotificationObjectResolver]
  });
```
Everything seems to be fine until I start using union type.
Users will receive notifications about Post or Post Comment, so I declare EntityUnion type like this:
```typescript
export const EntityUnion = createUnionType({
  name: "EntityUnion",
  types: [Post, PostComment]
});
```
and in the notification resolver I just return the entity:
```
  @FieldResolver(() => EntityUnion)
  entity(@Root() notificationObject: NotificationObject): typeof EntityUnion {
    return notificationObject.entity;
  }
```

When running the following query, the entity field on the admin server will be empty, but the mobile server returns it exactly as I expected.
```
query {
  notificationObjects {
    id
    content 
    entity {
      ... on Post {
        id
        content
      }
      
      ... on PostComment {
        id
        content
      }
    }
  }
}
```

The result from the admin server:
```json
{
  "data": {
    "notificationObjects": [
      {
        "id": 1,
        "content": "Hello",
        "entity": {}
      },
      {
        "id": 2,
        "content": "Bonjour",
        "entity": {}
      },
      {
        "id": 3,
        "content": "Xin chào",
        "entity": {}
      }
    ]
  }
}
```

The result from the mobile server:
```json
{
  "data": {
    "notificationObjects": [
      {
        "id": 1,
        "content": "Hello",
        "entity": {
          "id": 1,
          "content": "Post 1"
        }
      },
      {
        "id": 2,
        "content": "Bonjour",
        "entity": {
          "id": 2,
          "content": "Post 2"
        }
      },
      {
        "id": 3,
        "content": "Xin chào",
        "entity": {
          "id": 1,
          "content": "Post Comment 1"
        }
      }
    ]
  }
}
```

**To Reproduce**
https://github.com/bkstorm/type-graphql-union-error
Here is the repository to reproduce the issue.

**Expected behavior**
The entity field should be returned on both servers.

**Logs**

**Enviorment (please complete the following information):**
 - OS: macOS Catalina
 - Node: v12.6.0
 - Package version: 0.17.6
 - TypeScript version: 3.8.3

**Additional context**

**Comment by MichalLytek** [comment] 2020-03-20 06:46
Nultiple separate schemas are supported only in  `v0.18` - please install `type-graphql@beta` :wink:

**Comment by bkstorm** [comment] 2020-03-20 08:48
> Nultiple separate schemas are supported only in `v0.18` - please install `type-graphql@beta` 😉
Thank you but upgrading to 0.18.0-beta.11 doesn't fix my issue.

**Comment by MichalLytek** [comment] 2020-03-20 10:24
This is really weird error 😕 

I've reproduced that without apollo-server to confirm it's graphql issue.
Looks like only the last build schema is working properly.

The weird thing is that each schema has correct types definitions - the union exists in the docs (introspection).

So when I put `__typename` in the query, I got correct names of the types, but no data from unions 😱 

@bkstorm 
Can you reproduce that using pure `graphql-js`?

**Comment by bkstorm** [comment] 2020-03-20 14:13
Okay, I will try to reproduce this issue using graphql-js. Please wait!

**Comment by MichalLytek** [comment] 2020-03-20 14:15
Thanks! Just create all the object types and input types, and then do `new GraphQLSchema()` twice, using the same blocks

**Comment by bkstorm** [comment] 2020-03-20 15:08
https://github.com/bkstorm/graphql-js-union-error
here you go. I can't reproduce the issue with graphql-js.

**Comment by MichalLytek** [comment] 2020-03-20 18:18
Fixed via `bb53066`, published in `0.18.0-beta.12` 🎉 

@bkstorm let me know if the fix works for you 😉

**Closed by MichalLytek** 2020-03-20 18:18 UTC
Labels: Bug :bug:, Community  :family_man_girl:, Need More Info :man_shrugging:

**Comment by bkstorm** [comment] 2020-03-21 02:41
Thank you very much, it works 👍

**Comment by MichalLytek** [comment] 2020-03-21 12:17
@bkstorm 
Thanks again for the report 🙏 

I've realized that the same bug exists for interfaces, so I've also fixed that 💪 
https://github.com/MichalLytek/type-graphql/commit/253bb0e443a02d966ea2169284021fab3e12c642
