### ISSUE TITLE
Poor error message when @ObjectType implements contains class without annotations

### ISSUE THREAD

**Issue by gdanov** [MichalLytek/type-graphql#474] opened 2019-11-25 17:24 UTC
**Describe the bug**
I have `CRM.Client` and `ClientImpl` with the second being annotated as

`@tq.ObjectType({ implements: CRM.Client })
export abstract class ClientImpl extends CRM.Client {`

when CRM.Client is *not* annotated with `@InterfaceType` the error message has no data to help fix the issue.

The code throwing the error is at :
node_modules/type-graphql/dist/schema/schema-generator.js:157:59)

*** possible solution ***
something along the lines of:
```javascript
let interfaces = interfaceClasses.map(interfaceClass =>{
   let ifdef= this.interfaceTypesInfo.find(info => info.target === interfaceClass)
   if(ifdef) {return ifdef.type}
   else{ console.error("can't find interface definition for",interfaceClass," in ",objectType.target)  }
```

immediately gives away the culprit.

**Enviorment (please complete the following information):**
- type-graphql@  "version": "0.17.5"

**Comment by MichalLytek** [comment] 2019-11-25 17:30
Duplicate of #12 - @gdanov please add a comment in that issue 🔒

**Closed by MichalLytek** 2019-11-25 17:30 UTC
