### ISSUE TITLE
args are not validated before being passed to subscribe

### ISSUE THREAD

**Issue by backbone87** [MichalLytek/type-graphql#535] opened 2020-02-10 05:43 UTC
**Describe the bug**
Args are not validated before being passed to `subscribe`

**To Reproduce**
```
@ArgsType()
class MyArgs {
  @Field(() => String)
  @MinLength(1)
  public name!: string;
}

@Resolver()
export default class MySubscriptions {
  @Subscription(() => String, {
    subscribe: (root, { name }: MyArgs) => {
      return { next: async () => ({ done: true }) };
    },
  })
  public observe(@Args(() => MyArgs ) args: MyArgs): string {
    return args.name;
  }
}
```
-> Subscribe with name set to empty string
-> No error (error would occur on first resolver call, but we have empty observable, also it should not (re)validate on resolver call)

**Expected behavior**
Arguments being validated before being passed to subscribe

**Enviorment (please complete the following information):**
 - OS: Windows
 - Node: 12
 - Package version: 0.17.6
 - TypeScript version: 3.7

**Comment by MichalLytek** [comment] 2020-02-10 17:26
Kinda duplicate of #200 and #175 👀 

Middlewares stack was created before subscriptions and their dynamic topic or custom subscribe feature, so middlewares, validation and authorization happens for the `resolve` part of subscription, not before subscribing.

Custom `subscribe` means "escape from framework and do it by my own". You need to check the args by yourself.

I will leave it open for visibility purposes.

**Comment by backbone87** [comment] 2020-02-10 17:35
is it possible (= pretty straightforward) to extend/change the functionality? i would try to create a PR then

**Comment by MichalLytek** [comment] 2020-02-10 18:09
I doubt that, it's too complicated and too big breaking change I think.

The whole stack has to be redesigned and refactored to make it work properly and be customizable. I will do that in near future.

**Comment by MichalLytek** [comment] 2020-05-03 17:20
Closing as it will be covered in #200 and #542 🔒

**Closed by MichalLytek** 2020-05-03 17:20 UTC
Labels: Bug :bug:, Community  :family_man_girl:, Duplicate :key:
