### ISSUE TITLE
Allow Types to be decorated with @ObjectType()

### ISSUE THREAD

**Issue by cyberprodigy** [MichalLytek/type-graphql#523] opened 2020-01-15 15:23 UTC
**Is your feature request related to a problem? Please describe.**
In order to reduce required code it would be great to be able to decorate TypeScript types with @ObjectType()

**Describe the solution you'd like**
Say I have class ApplicationForm
```
@ObjectType()
class ApplicationForm {
   @Field(() => Int)
   public id: number;

   @Field(() => String)
   public title: string;

   @Field(() => String)
   public description: string;
} 
```

Then I want to use TS utility Omit on ApplicationForm to create SampleApplicationForm , which has no ID 
``` 
@ObjectType()
type SampleApplicationForm = Omit<ApplicationForm, "id"> 
```

**Describe alternatives you've considered**
I would like to know if there are any alternatives. The goal is to reduce repeating almost similar datatypes.
Often times the property is available but other times not. 
Also very common usecase is being able to specify that property is nullable or not depending on context of query/mutation called.

**Additional context**
N/A

**Comment by MichalLytek** [comment] 2020-01-15 15:29
Unfortunatelly, decorators cannot be applied on types as they are erased in compilation and not present in runtime. So you have to use classes, not types or interfaces.

Duplicate of #453 🔒

**Closed by MichalLytek** 2020-01-15 15:29 UTC
