### ISSUE TITLE
Schema name option for input fields

### ISSUE THREAD

**Issue by ziggy6792** [MichalLytek/type-graphql#1059] opened 2021-09-30 19:08 UTC
**Is your feature request related to a problem? Please describe.**

I am not sure if this is a bug or a feature request.

I have this input type

```
@InputType()
export class UpdateReelInput implements Partial<Reel> {
  @Field({ name: 'id' }) //HERE is am assigning a different name
  _id: ObjectId;

  @Field({ nullable: true })
  name: string;

  @Field({ nullable: true })
  description: string;

  ...
}
```

This mutation
```
@Mutation(() => Reel)
  async updateReel(@Arg('input', () => UpdateReelInput) input: UpdateReelInput): Promise<Reel> {
```

Which then call with this gql mutation

```
mutation updateReel($input: UpdateReelInput!){
  updateReel(input: $input){
    id
    definition
    description
  }
}
```

With this argument

```
{
  "input": {"id": "61530b2a582122227ab76672", "name": "new name", "description": "new description"}
}
```

I wold expect that the mutation that receives this the `input` variable equal to

```
{"_id": "61530b2a582122227ab76672", "name": "new name", "description": "new description"}
```

So the `id` input field should be renamed to `_id`

However the the `input` variable I actually receive is equal to
```
{"name": "new name", "description": "new description"}
```
There is no `id` or `_id` field

**Describe the solution you'd like**

I would like to able to use the `name` option property on `@InputType() -> @Field` to remap input field names to argument property names received in my mutation.

As I said I not sure if this a bug or a feature request.

**Additional context**

I want to do this because I am using mongoose/typegoose and I don't want my client to be 'aware' of the weird `_id` syntax that mongo is using and rather to just send id as `id` 

My code is here;
https://github.com/ziggy6792/type-graphql-feature-request 
https://github.com/ziggy6792/type-graphql-feature-request/blob/master/src/inputs/reel.input.ts (input with id)
https://github.com/ziggy6792/type-graphql-feature-request/blob/master/src/resolvers/reel.resolver.ts (resolver that receives input)

Thanks a lot and thanks for creating such a powerful and fun framework to work with

**Comment by MichalLytek** [comment] 2021-09-30 19:56
Duplicate of #346 🔒

**Closed by MichalLytek** 2021-09-30 19:56 UTC
