### ISSUE TITLE
Is it possible to add a mapping type helpers from Nest?

### ISSUE THREAD

**Issue by cloudever** [MichalLytek/type-graphql#679] opened 2020-08-13 02:05 UTC
**Is your feature request related to a problem? Please describe.**
Nest.js framework inlcude a few mapping type helper that allow to minimize repeating code  when developing CRUD for GraphQL. For example if there is a CreateUserInput, there is also UpdateUserInput that looks very similar and mapping type helpers allow to extend InputType

**Describe the solution you'd like**
Rewrite mapping type helpers from Nest.js

**Describe alternatives you've considered**
https://docs.nestjs.com/graphql/mapped-types

It's not possible to use mapping type helpers from nest.js with type-graphql project

**Comment by MichalLytek** [comment] 2020-08-13 07:52
Yes, it is possible to implement a feature proposed over a year before a NestJS implementation 😉 
It's on the roadmap for 1.x release.

Closing as duplicate of #453 🔒

**Closed by MichalLytek** 2020-08-13 07:52 UTC
