### ISSUE TITLE
Could we create a type-graphql-client?

### ISSUE THREAD

**Issue by jwjuele** [MichalLytek/type-graphql#612] opened 2020-04-20 22:08 UTC
Hey everyone!

this is certainly not the right place to post this, but i wanted to reach out to you guys, and ask whether you could have a glimpse on a decent try to create a type-graphql-client module.

It's based on a script that converts js objects into graphql queries and it purpose is to make our code more readable when working with graphlql.

https://github.com/jwjuele/type-graphql-client

Thanks in advance!

Greets Jules!

**Comment by MichalLytek** [comment] 2020-04-21 07:32
TypeGraphQL client is out of scope of this project, as discussed in #461.
It produces GraphQL schema that can be used with any standard GraphQL tool for client queries, so there's no need for a dedicated library, even if someone doesn't like the very good query language.

Using `type-graphql-` name prefix is ambiguous as it may suggest it's related or compatible with `type-graphql`. From what I see in readme, it's completly independent package that only uses the decorator pattern, with plenty of differences comparing to the original. So I would suggest trying a different name instead :wink: 

Closing as duplicate of #461 :lock:

**Closed by MichalLytek** 2020-04-21 07:32 UTC
