### ISSUE TITLE
directive graphql-rate-limit does not work

### ISSUE THREAD

**Issue by gyl89** [MichalLytek/type-graphql#1569] opened 2023-11-10 15:43 UTC
**Describe the Bug**
@rateLimit directive does not seem to work (coming from the package graphql-rate-limit-directive)

**To Reproduce**
Define resolverClasses (including one mutation with @rateLimit), then to build the schema, use the code
```
import {rateLimitDirective} from 'graphql-rate-limit-directive';
  ...
private async buildSchema(resolverClasses: any): Promise<GraphQLSchema> {
    const { rateLimitDirectiveTypeDefs, rateLimitDirectiveTransformer } = rateLimitDirective();


    const basicSchema = await buildSchema({
      authChecker: ({ context }, perms) => accessCheck(context, perms),
      resolvers: resolverClasses,
      container,
    });
    const schemaMergedWithTypes = mergeSchemas({
      schemas: [basicSchema],
      typeDefs: rateLimitDirectiveTypeDefs,
    });
    const schemaWithRateLimitDirective = rateLimitDirectiveTransformer(schemaMergedWithTypes);
    return schemaWithRateLimitDirective;
  }

...
```

**Expected Behavior**
When using "@rateLimit({ limit: 3, duration: 60 })" before a mutation, it should limit the rate at which the mutation can be called.

**Logs**
When building the schema through buildSchema:
`Error parsing directive definition "@rateLimit({ limit: 3, duration: 60 })"`

**Environment (please complete the following information):**

- OS: Mac os, docker environment
- Node 16-alpine.
- Package version : 2.0.0.beta3,
 "graphql-rate-limit-directive": "2.0.4"
- TypeScript version : 4.9.5

**Comment by MichalLytek** [comment] 2023-11-11 09:27
Directives should be passed to the `buildSchema` function. TypeGraphQL performs schema check after build, so it does not know the definition of your directive and yells.

**Comment by gyl89** [comment] 2023-11-13 10:00
Thanks for your answers. 

I feel thought that the documentation is not very clear :
https://typegraphql.com/docs/directives.html
Part on the 'fake-rename-directives" does not mention that. Besides, the package I mentioned does not export the directive but only the transformer and the typedefs.

**Comment by MichalLytek** [comment] 2023-11-13 13:38
Fair point. Maybe @carlocorradini can tell you more as he wrote this chapter (based on git blame).

For now, try to use `skipCheck: true` option of `buildSchema`.

**Comment by carlocorradini** [comment] 2023-11-18 12:20
Sorry for the late reply, I'll check it ASAP 🥳

**Comment by carlocorradini** [comment] 2023-11-19 13:13
@gyl89 
Strange... I'm using the same approach with [`graphql-auth-directive`](https://github.com/carlocorradini/graphql-auth-directive) (see <https://github.com/carlocorradini/graphql-auth-directive/blob/main/examples/typegraphql/index.ts>)
Can you create an example repo with the code so we can examine and test it? Thanks 😅🥳

**Comment by MichalLytek** [comment] 2024-01-06 16:59
@gyl89 Can you provide a repository with a minimal reproducible code example, in order to debug the issue?

**Comment by shadowbrush** [comment] 2024-06-03 19:26
FWIIW, it's working for me just like @carlocorradini describes:

```typescript
const schema = await buildSchema({
  resolvers,
  authChecker,
  pubSub: serviceHelpers.getPubSub(),
  globalMiddlewares: [ErrorInterceptorMiddleware],
})

const redisClient = new Redis(options)

const limiterOptions: IRateLimiterRedisOptions = {
  storeClient: redisClient,
  keyPrefix: 'grrl', // must be unique for limiters with different purpose
}

const keyGenerator = <TContext>(
  directiveArgs: RateLimitArgs,
  source: unknown,
  args: { [key: string]: unknown },
  context: TContext,
  info: GraphQLResolveInfo,
): string => {
  const defaultKey = defaultKeyGenerator(directiveArgs, source, args, context, info)
  return `${(context as GraphQlContext).user?.id || (context as GraphQlContext).req.ip}:${defaultKey}`
}

class DebugRateLimiterRedis extends RateLimiterRedis {
  consume(
    key: string | number,
    pointsToConsume?: number,
    options?: { [key: string]: any }
  ) {
    console.log(`[CONSUME] ${key} for ${pointsToConsume}`);
    return super.consume(key, pointsToConsume, options);
  }
}

const {
  rateLimitDirectiveTypeDefs,
  rateLimitDirectiveTransformer,
} = rateLimitDirective({
  name: 'rateLimit',
  keyGenerator,
  limiterClass: DebugRateLimiterRedis,
  limiterOptions,
})

const mergedSchema = mergeSchemas({
  schemas: [schema],
  typeDefs: [rateLimitDirectiveTypeDefs]
})

const newSchema = rateLimitDirectiveTransformer(mergedSchema)
```

And in the resolvers, adding: `@Directive('@rateLimit(limit: 30, duration: 60)')` does not throw up any errors.

**Comment by carlocorradini** [comment] 2024-06-03 22:02
Nice

**Comment by MichalLytek** [comment] 2024-06-04 05:55
So closing as cannot reproduce 🔒

**Closed by MichalLytek** 2024-06-04 05:55 UTC
Labels: Question :grey_question:, Need More Info :man_shrugging:
