### ISSUE TITLE
Union type is not working as input property type.

### ISSUE THREAD

**Issue by fider-apptimia** [MichalLytek/type-graphql#1034] opened 2021-09-17 11:14 UTC
**Describe the Bug**
Union type is not working as input property type.

**To Reproduce**
```typescript
@InputType()
export class DataA {
  @Field()
  a!: string;
}

@InputType()
export class DataB {
  @Field()
  b!: string;
}

const DataUnion = createUnionType({
  name: 'DataUnion',
  types: () => [DataA, DataB] as const,
  resolveType: value => {
    if ((value as DataA).a) {
      return DataA.name;
    }
    if ((value as DataB).b) {
      return DataB.name;
    }
    return undefined;
  }
});

@InputType()
export class MyQueryInput {
  // other fileds...

  @Field(() => DataUnion, { nullable: true })
  myUnion?: DataUnion | null;
}
```

**Expected Behavior**
No runtime error.

**Logs**
```
    Cannot determine GraphQL input type for 'myUnion' of 'MyQueryInput' class. Is the value, that is used as its TS type or explicit type, decorated with a proper decorator or is it a proper input value?

      at Function.getGraphQLInputType (../../../common/temp/node_modules/.pnpm/type-graphql@1.1.1_82b96689edac18646b8edb6218fb25f5/node_modules/type-graphql/dist/schema/schema-generator.js:540:19)
      at ../../../common/temp/node_modules/.pnpm/type-graphql@1.1.1_82b96689edac18646b8edb6218fb25f5/node_modules/type-graphql/dist/schema/schema-generator.js:316:47
          at Array.reduce (<anonymous>)
      at fields (../../../common/temp/node_modules/.pnpm/type-graphql@1.1.1_82b96689edac18646b8edb6218fb25f5/node_modules/type-graphql/dist/schema/schema-generator.js:314:55)
      at resolveThunk (../../../common/temp/node_modules/.pnpm/graphql@15.5.2/node_modules/graphql/type/definition.js:480:40)
      at defineInputFieldMap (../../../common/temp/node_modules/.pnpm/graphql@15.5.2/node_modules/graphql/type/definition.js:1207:18)
      at GraphQLInputObjectType.getFields (../../../common/temp/node_modules/.pnpm/graphql@15.5.2/node_modules/graphql/type/definition.js:1155:27)
      at collectReferencedTypes (../../../common/temp/node_modules/.pnpm/graphql@15.5.2/node_modules/graphql/type/schema.js:376:81)
      at collectReferencedTypes (../../../common/temp/node_modules/.pnpm/graphql@15.5.2/node_modules/graphql/type/schema.js:372:11)
      at new GraphQLSchema (../../../common/temp/node_modules/.pnpm/graphql@15.5.2/node_modules/graphql/type/schema.js:157:7)
```

**Environment:**

- OS Ubuntu 20.04.3 LTS
- Node version 14.17.6
- Package version 1.1.1
- TypeScript version 4.4.2

**Additional Context**
I've tried also with additional `@ObjectType('...')` next to `@InputType('...')`, same result - not working.

**Comment by MichalLytek** [comment] 2021-09-17 11:34
Duplicate of #384 - not supported by GraphQL spec 🔒

**Closed by MichalLytek** 2021-09-17 11:34 UTC
