### ISSUE TITLE
serverless-offline: typedefs being imported many times >.<

### ISSUE THREAD

**Issue by githubflub** [MichalLytek/type-graphql#443] opened 2019-10-15 05:24 UTC
When I run `>serverless offline` in my terminal, it creates an http endpoint and a websocket endpoint. I make a request to the HTTP endpoint, type-graphql tries to build the schema but fails with the age old error. 

`Error: Schema must contain uniquely named types but contains multiple types named "User".`

I comment out most of the code in the lambda function that is the websocket endpoint and run `serverless offline` again. Everything works. 

I've narrowed down the issue to the typedefs being "imported" multiple times (probably due to there being either 2 endpoints or 2 functions - currently I have only 1 function per endpoint). 

Here is how it looks when it works (imports commented out). 
![Annotation 2019-10-15 001418](https://user-images.githubusercontent.com/18061353/66808776-c7949800-eee0-11e9-8f1c-e529c6963e72.png)
![Annotation 2019-10-15 001134](https://user-images.githubusercontent.com/18061353/66808625-78e6fe00-eee0-11e9-85e4-7ac1c63e1db4.png)

Here is how it looks when I import a typedef from the websocket endpoint. Definitely imported multiple times... 
![Annotation 2019-10-15 001535](https://user-images.githubusercontent.com/18061353/66808899-0e828d80-eee1-11e9-9e81-97d4c326f7aa.png)
![Annotation 2019-10-15 001954](https://user-images.githubusercontent.com/18061353/66809335-06771d80-eee2-11e9-8edd-d12d8a828d5d.png)

And the error 
![Annotation 2019-10-15 002428](https://user-images.githubusercontent.com/18061353/66809427-32929e80-eee2-11e9-9093-020716006a3a.png)

Maybe this is a question for serverless-offline... What do you guys think? What is the problem with the typedefs being imported multiple times? Is there something I can do to stop this?

**Comment by MichalLytek** [comment] 2019-10-15 07:57
Duplicate of #96 #162 🔒

**Closed by MichalLytek** 2019-10-15 07:57 UTC

**Comment by githubflub** [comment] 2019-10-16 05:31
Thank you for pointing me in the right direction. The solution here appears to have fixed the problem for me. 

https://github.com/MichalLytek/type-graphql/issues/162#issuecomment-513566403
