### ISSUE TITLE
Jest does not cover decorators with parameters

### ISSUE THREAD

**Issue by camo-f** [MichalLytek/type-graphql#506] opened 2020-01-02 13:21 UTC
**Describe the bug**
When using Jest coverage, decorators with additional parameters appear as uncovered :
- `@Field(type => ID)`
- `@Field(type => [Team])`
- `@Query(returns => User)`
- `@Mutation(returns => User)`
- Plain decorators such as `@Field()` are covered.

**To Reproduce**
User class
```
@ObjectType()
export class User {
  @Field(type => ID)
  @IsMongoId()
  _id!: Types.ObjectId;

  @Field()
  @IsEmail()
  email!: string;

  @Field()
  @IsString()
  name!: string;

  @Field(type => [Team])
  @IsArray()
  teams?: Team[];
}
```

User resolver
```
@Resolver(of => User)
export class UserResolver {
  constructor(private readonly usersService: UserService) {}

  @Query(returns => User)
  async user(@Args('id') id: string): Promise<User> {
    const user = await this.usersService.findById(id);
    if (!user) {
      throw new NotFoundException(id);
    }
    return user;
  }

  @Query(returns => [User])
  async users(): Promise<User[]> {
    return await this.usersService.findAll();
  }

  @Mutation(returns => User)
  @UsePipes(new ValidationPipe())
  async addUser(
    @Args('addUserInput') addUserInput: AddUserInput
  ): Promise<User> {
    return await this.usersService.add(addUserInput);
  }
}
```

Jest output
```
src/user                    |    92.54 |      100 |    72.22 |       91.8 
  user.model.ts             |    89.47 |      100 |        0 |      88.24 
  user.resolver.ts          |    86.36 |      100 |     62.5 |         85 
```

**Expected behavior**
Decorators should be covered

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.

**Environment (please complete the following information):**
 - OS: Linux Alpine 3.10.3
 - Node v13.3.0
 - Package v0.17.5
 - TypeScript v3.6.3

**Additional context**
 - Jest v24.9.0
 - Typegoose v6.1.8
 - NestJS 6

Did I miss something ? I read issue #377 but didn't find a solution.
Thank you !

**Comment by MichalLytek** [comment] 2020-01-02 14:01
> decorators with additional parameters appear as uncovered

I think that only parameters, not the whole decorator call is uncovered.
If you want to avoid such things, use `_type => User` or `() => User` syntax.

**Comment by camo-f** [comment] 2020-01-02 15:04
It is indeed only with functions as parameters, though `@Resolver(of => User)` decorator is covered.

I tried both your suggestions, none of them get covered.

**Comment by MichalLytek** [comment] 2020-01-02 15:08
`@Resolver` is always called, the callback `of => User` only when you use `@FieldResolver` on some of its methods.

**Comment by camo-f** [comment] 2020-01-02 15:26
I don't understand how I should unit-test them. I made the following test file for the resolver, so each decorator should get covered, right ?
```
describe('UserResolver', () => {
  let resolver: UserResolver;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [UserResolver, UserService]
    }).compile();

    resolver = module.get<UserResolver>(UserResolver);
  });

  it('should be defined', () => {
    expect(resolver).toBeDefined();
  });

  it('should return all users', async () => {
    expect(await resolver.users()).toStrictEqual(users);
  });

  it('should return a single user', async () => {
    expect(await resolver.user('5dfb9aedd8b56d001b4c1362')).toBe(users[0]);
  });

  it('should throw an exception', async () => {
    try {
      await resolver.user('5dfb9aedd8b56d001b4c1363');
    } catch (error) {
      expect(error).toBeInstanceOf(NotFoundException);
    }
  });

  it('should add a user', async () => {
    expect(await resolver.addUser(addUserInput)).toBe(users[0]);
  });
});
```

**Comment by MichalLytek** [comment] 2020-01-02 15:46
Just use:
```ts
@Resolver() // without callback
export class UserResolver {}
```
when you don't have a field resolver.

And 
```ts
  @Field(() => ID) // without args
  @IsMongoId()
  _id!: Types.ObjectId;
```
for other cases

**Comment by camo-f** [comment] 2020-01-02 16:23
I'm sorry, I don't understand everything. Based on what you wrote and the doc, I should :
- specify a type for `@Field()` when it isn't a simple type (e.g. ID or any complex type I defined elsewhere, but in that case it's not covered)
- specify a type for `@Resolver()` when resolver has field resolvers
- specify a return type for `@Query` and `@Mutation`

If this is correct, does it mean that field decorators with complex types and query/mutation can't be covered ?

**Comment by MichalLytek** [comment] 2020-01-02 16:34
> If this is correct,

Yes

> field decorators with complex types and query/mutation can't be covered ?

Why do you think so?

It shows you the lines as not covered because you don't use `type` or `returns` parameter in the callback body.

**Comment by camo-f** [comment] 2020-01-03 08:44
I went through the documentation again, I don't get how I should use `type` and `returns` parameters

**Comment by MichalLytek** [comment] 2020-01-03 08:57
They can't be consumed as their type is `void`. They acts just like a description, a documentation, to make the code easier to read.

**Comment by camo-f** [comment] 2020-01-03 09:00
So that's what I'm saying, I can't cover them, right ?

**Comment by MichalLytek** [comment] 2020-01-03 09:07
Fuck yes! As I said - use `@Resolver()` without callback and `@Field(() => ID)` without args.

Nothing more I can do, so closing this issue 🔒

**Closed by MichalLytek** 2020-01-03 09:07 UTC
Labels: Need More Info :man_shrugging:, Question :grey_question:

**Comment by camo-f** [comment] 2020-01-03 09:13
I already tried your suggestion to omit args with `@Field(() => ID)` and `@Query(() => User)`, but it still appears as uncovered.
Thank you for your time anyway.

**Comment by MichalLytek** [comment] 2020-01-03 09:15
So please post an issue on the Jest repo that it doesn't properly report coverage for decorators.

**Comment by yehonadav-feel** [comment] 2022-07-06 07:10
if there's any progression for this in jest, please someone post a link here so we can resolve our coverage issues

**Comment by TiavinaRakotobe** [comment] 2022-12-14 16:53
> `export const returingUser = () => User;`
> 
> then in ur decorator `@Query(returningUser)`

**Comment by johnnyschneider** [comment] 2024-05-15 15:12
> `export const returingUser = () => User;`
> 
> then in ur decorator `@Query(returningUser)`

I'm not sure I follow, all this did for me was migrate the coverage from the calling Query decorator to a separate LoC. Could you help me out with what I'm missing?

**Comment by simplenotezy** [comment] 2024-08-09 16:24
> `export const returingUser = () => User;`
> 
> then in ur decorator `@Query(returningUser)`

This works, but why? It's not that pretty having to do that in a resolver with a lot of queries. Is there another way around this?

**Comment by scelcov** [comment] 2025-03-26 09:00
Resolved coverage issues caused by inline `() => Type` usage in decorators by using a `returnTypeFn` helper across the project.

Usage example:

```ts
@Args('input', { type: returnTypeFn(MyDTO) })

**Comment by scelcov** [comment] 2025-03-26 09:01
Resolved coverage issues caused by inline `() => Type` usage in decorators by using a `returnTypeFn` helper across the project.

Usage example:

```ts
const returnTypeFn =
  <T>(type: T) =>
  () =>
    type;

@Args('input', { type: returnTypeFn(MyDTO) })
