### ISSUE TITLE
enum not returning expected value

### ISSUE THREAD

**Issue by cyberprodigy** [MichalLytek/type-graphql#507] opened 2020-01-03 11:47 UTC
**Describe the bug**
Enum is returning String when Int is expected

**To Reproduce**
Have an enum as this

```
export enum Status {
  PROGRESS = 0,
  READY = 1,
  FAIL = 2,
}

registerEnumType(Status, { name: "Status" });
```

Have an object like this

```
@ObjectType()
export class Job {
  @Field(() => Int)
  public id: number;

  @Field(() => Status)
  public status: Status;
}

```

**Expected behavior**
When querying, the resolver will resolve Job's status as String, but Int is expected

**Workarround**
Specify Status as Int

```
  @Field(() => Int)
  public status: Status;
```

**Logs**
N/A

**Enviorment (please complete the following information):**
 - OS: Ubuntu
 - Node v10.17.0
 - Package version 0.17.5
 - TypeScript version : 3.7.3

**Additional context**
N/A

**Comment by MichalLytek** [comment] 2020-01-03 11:49
Duplicate of #116 #486 🔒

**Closed by MichalLytek** 2020-01-03 11:49 UTC
