### ISSUE TITLE
`registerEnumType` is not a named export after compilation

### ISSUE THREAD

**Issue by nemanjastanic** [MichalLytek/type-graphql#1598] opened 2024-01-04 16:52 UTC
**Describe the Bug**
I started having this issue after upgrading from `2.0.0-beta.2` to `2.0.0-beta.4`. I can confirm this because it was fixed after downgrading to `2.0.0-beta.3`.

I am using SWC to compile my project.

**To Reproduce**
```ts
import { registerEnumType } from "type-graphql";

export enum SendTo {
  Channel = "Channel",
  Contact = "Contact",
}

registerEnumType(SendTo, {
  name: "SendTo",
});
```

The following snippet will fail with these configurations.

`.swcrc`
```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "isModule": true,
  "jsc": {
    "target": "esnext",
    "preserveAllComments": false,
    "experimental": { "keepImportAssertions": true },
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true,
      "dts": true
    },
    "baseUrl": ".",
    "paths": {}
  }
}
```

`tsconfig.json`
```json
{
  "extends": "@secret/tsconfig/base.json",
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": "./src",
    "outDir": "dist",
    "jsx": "preserve",
    "types": ["node", "reflect-metadata"],
    "paths": {}
  },
  "include": ["./src/**/*"],
  "exclude": ["dist", "node_modules"]
}
```

**Expected Behavior**
The function is imported without any issues.

**Logs**
![Screenshot 2024-01-04 at 5 45 09 PM](https://github.com/MichalLytek/type-graphql/assets/105949556/781876a8-c247-4d35-b537-7d736004e052)

**Environment (please complete the following information):**

- OS: MacOS 14.0
- Node: 18.18.2
- Package version: 2.0.0-beta.4
- TypeScript version: 5.3.3

**Comment by MichalLytek** [comment] 2024-01-05 13:44
@carlocorradini Might this be related to ESM support?

**Comment by carlocorradini** [comment] 2024-01-05 13:52
ESM code is using `require` instead of `import`:
![Screenshot_2024-01-05-14-50-46-14_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/MichalLytek/type-graphql/assets/21266147/a5efc038-f70d-422a-8c52-b1683b740703)


@MichalLytek How did you build the package?
I'll try locally to check if this is due to an upgrade of a dependency

**Comment by carlocorradini** [comment] 2024-01-05 14:01
@MichalLytek I confirm is the build process

**Comment by carlocorradini** [comment] 2024-01-05 14:17
@MichalLytek I've tried downgrading to `typescript v5.1.6` (same as v.2.3) and manually:
```sh
npx tsc --build ./tsconfig.esm.json
```
And it does not works.
It looks like `typescript` is ignoring `esm`... WTF 😅

**Comment by MichalLytek** [comment] 2024-01-05 14:33
It was working as we've published beta 3 via gh actions 😄

**Comment by MichalLytek** [comment] 2024-01-05 14:38
I guess this was me doing deps upgrade without checking build results:

![Code_Ozb9w4fl7J](https://github.com/MichalLytek/type-graphql/assets/10618781/897b7aaf-5cb1-4f69-9d4c-c579892089f6)

![image](https://github.com/MichalLytek/type-graphql/assets/10618781/71e45b11-ef24-4c63-91a0-63d32d9a46e6)

We now can't trick typescript to emit ESM for commonjs project, we need a real ESM project to emit ESM code.

**Comment by carlocorradini** [comment] 2024-01-05 15:06
@MichalLytek Yup, I've tried and we can't trick TypeScript anymore

**Comment by MichalLytek** [comment] 2024-01-06 16:55
Should be fixed by 51ff280, will see in `beta.5` if that works 😉

**Closed by MichalLytek** 2024-01-06 16:55 UTC
Labels: Bug :bug:, Community  :family_man_girl:, Need More Info :man_shrugging:

**Comment by nemanjastanic** [comment] 2024-01-07 20:16
Thanks!

**Comment by maplesteve** [comment] 2024-01-10 17:40
> Published v5, please check now if it works 😉

@MichalLytek the v5-package is [nearly empty](https://www.npmjs.com/package/type-graphql/v/2.0.0-beta.5?activeTab=code); the `build` directory is missing.

**Comment by dahaupt** [comment] 2024-01-11 00:04
@MichalLytek I can confirm that the `build` directory is missing in `2.0.0-beta.5`.

**Comment by MichalLytek** [comment] 2024-01-11 07:40
Thanks for the report. Our publish workflow is not working so I do publish by myself and something went wrong.

Should be ok now with `2.0.0-beta.6`.

**Comment by carlocorradini** [comment] 2024-01-11 08:57
Apologize if the CI/CD is currently broken 😔
It's my fault
I'll fix it ASAP
