### ISSUE TITLE
Hello, we want to support `graphql` v16.6.0

### ISSUE THREAD

**Issue by kxbin** [MichalLytek/type-graphql#1386] opened 2022-11-22 07:54 UTC
**Is your feature request related to a problem? Please describe.**

Now `Apollo Server 4` already supports the lowest supported `graphql` version v16.6.0, so `type-graphql` is not compatible with `Apollo Server 4`

**Describe the solution you'd like**

As a popular graphql server, `Apollo Server 4` provides many new and useful things. I think we need to keep moving.

Now we directly change the `graphql` version to ^16.6.0 in package.json dependencies. Will there be any compatibility issues? 

If there are compatibility issues, what places need to be modified together?

**Comment by MichalLytek** [comment] 2022-11-22 08:01
Duplicate of #1100. See #1331 🔒

**Closed by MichalLytek** 2022-11-22 08:01 UTC
