### ISSUE TITLE
When multiple resolvers throw an error, the `errors` array in the response only contains one error

### ISSUE THREAD

**Issue by bageren** [MichalLytek/type-graphql#1661] opened 2024-03-26 16:50 UTC
**Describe the Bug**
When multiple resolvers throw an error, the `errors` array in the response only contains one error.

**To Reproduce**

1. Create a resolver with 2 field resolvers inside.
2. Throw an error inside both field resolvers
3. Start up the graphql server (I used @apollo/server@4.7.1)
4. Send a query to the server that triggers both field resolvers

Something like this:

```
@ObjectType()
class Recipe {
  @Field(() => ID)
  id: string | undefined;

  @Field()
  title: string | undefined;
}

@Resolver(() => Recipe)
export class RecipeResolver {
  @Query(() => Recipe)
  async recipe() {
    return {};
  }

  @FieldResolver()
  async id(): Promise<any> {
    throw new Error("id error");
  }

  @FieldResolver()
  async title(): Promise<any[]> {
    throw new Error("title error");
  }
}
```

**Expected Behavior**
The `errors` array in the response should include both errors, something like:

`{
  "data": {},
  "errors": [
    {
      "message": "id error",
    },
   {
      "message": "title error",
   }
   ]
}
`

**Logs**

**Environment (please complete the following information):**

- OS: MacOS 14.4
- Node: v18.17.0
- Package version: 2.0.0-beta.6
- TypeScript version: ^5.4.3

**Additional Context**

**Comment by MichalLytek** [comment] 2024-03-26 18:16
Can you reproduce this with using pure `graphql-js` lib?

**Comment by bageren** [comment] 2024-03-26 18:34
> Can you reproduce this with using pure `graphql-js` lib?

Yes

```
import { graphql } from "graphql";
graphql({
  schema,
  source: `query ExampleQuery {
  recipe {
    id
    title
  }
}`,
}).then((d) => console.log(d.errors.length));
// logs 1
```

**Comment by MichalLytek** [comment] 2024-03-26 18:37
I mean try to build the types and resolvers with `graphql-js` constructs, without TypeGraphQL.

**Comment by bageren** [comment] 2024-03-26 18:52
> I mean try to build the types and resolvers with `graphql-js` constructs, without TypeGraphQL.

```
const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: "RootQueryType",
    fields: {
      recipe: {
        type: new GraphQLObjectType({
          name: "Recipe",
          fields: {
            id: {
              type: GraphQLString,
              resolve: () => {
                throw new Error("id error");
              },
            },
            title: {
              type: GraphQLString,
              resolve: () => {
                throw new Error("title error");
              },
            },
          },
        }),
        resolve() {
          return {};
        },
      },
    },
  }),
});

graphql({
  schema,
  source: `query ExampleQuery {
  recipe {
    id
    title
  }
}`,
}).then((d) => console.log(d.errors.length));
// logs 2
```

**Comment by MichalLytek** [comment] 2024-04-24 13:23
Closing as works as intended 🔒 

Explanation:
GraphQL runtime is designed to "swallow" errors - bubble it up, until it reaches nullable type. Then it places `null` for that part of response data tree and continue execution for other fields. Then it returns data and all the errors captured and "swallowed" during execution.
When there's no nullable field, it returns `data: null` and only the current error. Why? Because the rest of the field resolver could be not even called yet.
To see that behavior, all you need is to modify your `graphql-js` example and use `GraphQLNonNull` which is implicit in TypeGraphQL:

```ts
const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: "RootQueryType",
    fields: {
      recipe: {
        type: new GraphQLObjectType({
          name: "Recipe",
          fields: {
            id: {
              type: new GraphQLNonNull(GraphQLString),
              resolve: async () => {
                throw new Error("id error");
              },
            },
            title: {
              type: new GraphQLNonNull(GraphQLString),
              resolve: async () => {
                throw new Error("title error");
              },
            },
          },
        }),
        async resolve() {
          return {};
        },
      },
    },
  }),
});
```

Then the response does not contain both errors:

![image](https://github.com/MichalLytek/type-graphql/assets/10618781/5a752c02-ed36-42e9-b554-f48d0bff2142)

**Closed by MichalLytek** 2024-04-24 13:23 UTC
Labels: Bug :bug:, Community  :family_man_girl:
