### ISSUE TITLE
[Docs] Clarify field renaming is not working for InputType

### ISSUE THREAD

**Issue by lucasterra** [MichalLytek/type-graphql#815] opened 2021-03-13 19:28 UTC
**Describe the Bug**
Renaming fields with `@Field({ name: 'newName' })` for `@InputType` is not properly transforming the input object into the class object.

**To Reproduce**
Check PR this with the failing test cases: https://github.com/MichalLytek/type-graphql/pull/816

Create an `@InputType` class and add field renaming parameters.
```ts
@InputType
class MyInputType {
  @Field({ name: 'renamedFieldName' })
  fieldName: string;
}

@Mutation()
someMutation(@Arg('input') input: MyInputType) {
  // 
}
```

**Expected Behavior**
When calling a mutation with
```gql
someMutation(input: { renamedFieldName: "30" })
```
I expected to receive an object with:
```ts
MyInputType {
  fieldName: "30"
}
```
but I get:
```ts
MyInputType {

}
```

**Logs**
N/A

**Environment (please complete the following information):**

- OS: Linux
- Node v14.15.1
- Package version 1.1.1 (also doesn't work on latest master)
- TypeScript version (e.g. 4.2.2)

**Additional Context**
N/A

**Comment by MichalLytek** [comment] 2021-03-13 19:38
There's no such feature as renaming input fields. Renaming works only for output types as input fields has no resolvers that could translate one field value info other property value.

Docs doesn't mention such capabilities as renaming input fields, so it's not a bug.
Maybe it should be stated clear and sound that this works only for object types and interface type.

**Comment by lucasterra** [comment] 2021-03-13 19:44
Makes sense. Thanks @MichalLytek.

**Comment by MichalLytek** [comment] 2021-03-13 19:55
Reopening as it's quite common question actually. So I want to patch the docs 😉

**Comment by MichalLytek** [comment] 2021-03-14 19:35
Closing via 3733b1e 🔒

**Closed by MichalLytek** 2021-03-14 19:35 UTC
Labels: Community  :family_man_girl:, Documentation :book:
